# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1ef787decf34d70676e219e420e58782c0e09405eb07f775fb8e50f28c177a4732e340c2f0aace98f940bc3f9bce82e69f0133f0ee96771570bcc63ddbc908

test:
  secret_key_base: 7f93fa693f0e71d480607a65ea9ea45fc89cb21b78b8e0fdd675f059d659320df0b68c4255d9f4f4efc85093dcf2a7761c9a0603f651c9a16747940da9583388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
